---
abstract: 'SMTP support for IO::Async'
author:
  - 'Tom Molesworth <tom@entitymodel.com>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::Fatal: '0.010'
  Test::More: '0.98'
  perl: '5.010001'
configure_requires:
  ExtUtils::MakeMaker: '6.48'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.014, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Async-SMTP
recommends:
  Email::Simple: '0'
  IO::Async::Resolver::DNS: '0.04'
  IO::Async::SSL: '0.14'
requires:
  Future: '0.24'
  IO::Async: '0.54'
  IO::Socket::SSL: '0'
  Protocol::SMTP: '0.001'
  parent: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Net-Async-SMTP
  homepage: http://search.cpan.org/dist/Net-Async-SMTP/
version: '0.001'
